baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputFormats.archives]
baseName = "archive"
isPlainText = true
mediatype = "text/html"
notAlternative = true

[outputs]
page = ["HTML", "archives"]